[package]
name = "lodconv"
version = "0.1.0"
edition = "2021"
authors = ["HideBa"]
description = "A tool to convert LoD2.2 building models to LoD1.2"

[dependencies]
cgmath = "0.18.0"
thiserror = "2.0.12"
clap = { version = "4.5", features = ["derive"] }
rerun = "0.22.1"
